### ISSUE TITLE
Please add unit tests and improve README

### ISSUE THREAD

**Issue by mrtnzlml** [gplopes/rn-t9-keyboard#1]
Hi Gabriel 👋! Thanks for submitting your solution. Could you please add unit tests for your _"server"_ logic? We need to be sure you know how to write such tests.

Also, please add some basic information to the README file. It would be great to know what commands are needed in order to run and test the application because every app is very specific...

Thank you very much!

**Comment by gplopes** [comment]
Hey @mrtnzlml, sure it won't be a problem. I will need a couple of days to do so and I will ping you.

**Comment by gplopes** [comment]
hey @mrtnzlml, I have updated the repo. you can have a look at the **server/t9** test functionalities, as well as the README. 👍

**Comment by mrtnzlml** [comment]
Thanks. Someone will let you know.
